### ISSUE TITLE
Error while using LogHelper to parse a .xes file

### ISSUE THREAD

**Issue by davidglavas** [yosid16/EDU-ProM#6]
I'm trying to use [LogHelper](https://github.com/yosid16/EDU-ProM/blob/master/src/main/java/org/eduprom/utils/LogHelper.java) to parse the [BPI 2012 dataset](http://www.win.tue.nl/bpi/doku.php?id=2012:challenge):

```
	public static void main(String[] args) {
		
		XLog targetLog = null;
	
		String filePath = "financial_log.xes";
		
		// attempts to parse with universal Parser
		LogHelper t = new LogHelper();
		
		try {
			t.checkFile(filePath);	// makes sure that specified path is correct
			
			targetLog = t.readXes(filePath);	// parses .xes file, stores it as Xlog
			
		} catch (LogFileNotFoundException e) {
			System.out.println("File not Found, check the filepath. ");
			e.printStackTrace();
		} catch (ParsingException e) {
			System.out.println("Error while parsing the file. ");
			e.printStackTrace();
		}

		
		System.out.println("Dataset is loaded.");		
	}
```

When running this I get the following error message:
```
Unknown extension: http://www.xes-standard.org/meta_time.xesext
Unknown extension: http://www.xes-standard.org/meta_life.xesext
Unknown extension: http://www.xes-standard.org/meta_org.xesext
Unknown extension: http://www.xes-standard.org/meta_concept.xesext
Unknown extension: http://www.xes-standard.org/meta_3TU.xesext
Unknown extension: http://www.xes-standard.org/meta_general.xesext
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.deckfour.xes.util.XsDateTimeConversion.parseXsDateTime(XsDateTimeConversion.java:96)
	at org.deckfour.xes.util.XsDateTimeConversionJava7.parseXsDateTime(XsDateTimeConversionJava7.java:129)
	at org.deckfour.xes.in.XesXmlParser$XesXmlHandler.startElement(XesXmlParser.java:292)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1375)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2706)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:532)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
	at org.deckfour.xes.in.XesXmlParser.parse(XesXmlParser.java:175)
	at org.deckfour.xes.in.XParser.parse(XParser.java:108)
	at org.deckfour.xes.in.XUniversalParser.parse(XUniversalParser.java:77)
	at model.LogHelper.readXes(LogHelper.java:100)
	at model.Client.main(Client.java:64)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 21 more
```

I don't understand the problem. Am I using the parser incorrectly?

My final goal is to use the loaded XLog file and call something like the `mine()` method from [here](https://svn.win.tue.nl/repos/prom/Packages/EpisodeMiner/Trunk/src/org/processmining/models/episode_leemans/EpisodeMinerImpl.java). Is this possible? Note that I don't have ProM installed.

**Comment by davidglavas** [comment]
Error disappeared after I switched my JDK from OpenJDK 11 to Oracle's JDK 8.
